### ISSUE TITLE
Maps location not working

### ISSUE THREAD

**Issue by manuhuerta** [balopez83/Surface_Pro_3_Hackintosh#11]
When I open Maps app it shows an error that WiFi is not enabled and that cannot get accurate location.  I'm using USB wifi dongle.
When checking System Properties, indeed Wifi shows off
Rest of internet enabled apps works ok: Safari, iMessage, FaceTime, App Store, Photos, etc

Surface Pro 3 i5, 8GB RAM 
Ventura 13.3.1, using latest EFI you released

**Comment by balopez83** [comment]
Hi @manuhuerta , This is a known issue that cannot be resolved. macOS does not allow for using external Wi-Fi modules for location services and only uses built-in hardware on real macs. Because of this Wi-Fi will work but Apple maps will never give a precise location. Everything else in maps should work except for precise location. 

You might be able to get an external GPS unit and/or its possible it might work using an iPhone as a hotspot but haven't tested that.
