### ISSUE TITLE
clarification question on dual boot with windows 11

### ISSUE THREAD

**Issue by BT-Lim2021** [balopez83/Surface_Pro_3_Hackintosh#15]
Hi @balopez83,

First, Thank You so much for doing such great work.
I have been able to follow your instructions and successfully installed Big Sur on my Surface Pro 3.

I am a little unclear on dual booting with Windows 11 though.
Steps I have taken:
1. Installed Window 11
2. Installed Big Sur on a partition in internal SSD
3. moved /EFI/Microsoft to root of EFI
4. took care of secure boot per your instruction.

At this point, I can restart and OpenCore will show only 1 option: MacOS.

5. Moved /EFI/Microsoft folder back to its original place

At this point, as you pointed out, It will boot into Windows 11 automatically.

6. If I use the USB installer to boot, I see Open Core with MacOS, and Windows 11 option, as well as Installer Option.

7.  I tried to follow your instruction to enter UEFI shell and execute bcfg boot add command, but I am unable to get to the shell.  FN+F1 does not seem to do anything.  It still boots to Windows 11.

Am I mis-understanding things?  Is it possible to dual boot with Windows 11 without USB?  Is there a step that I missed?

Thanks for your help.  Sorry if my question is too elementary.

**Comment by BT-Lim2021** [comment]
Hi @balopez83 ,

Quick Update.  I have been able to dual boot through OpenCore.
Steps:
1. rename /EFI/Microsoft to /EFI/Microsoft11
2. Then add entry in Config.plist:  Misc > BlessOverride > \EFI\Microsoft11\Boot\bootmgfw.efi

Not sure if there is a better way to do this.

However, I noticed another issue in Windows 11.
When boot to Windows 11 from OpenCore, it does not show battery in Windows 11.  It thinks no battery installed.
This is the same situation whether I boot from OpenCore from USB or SSD.

If I rename \EFI\Microsoft folder back and boot straight to Windows 11, the battery show up properly.

I have done a little digging, found this same issue in Reddit, and solution posted (in screen shot) but I don't know how to make this change.  Can you help or point me how I can do this?

Thank You.
![Screenshot 2023-06-04 at 11 32 48 AM](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/132913336/41a901ef-1e6f-4893-98ae-0f6de925a2ea)

**Comment by balopez83** [comment]
Hi @BT-Lim2021 sorry it took me so long to get back to you. It looks like you found a suitable solution to resolve the dual boot issues. The Surface Pro 3 has a very troublesome UEFI which will always try to boot Windows if it can. Since your solution to dual booting is sufficient there is no reason to worry about changing it as it won't hurt things. 

Your battery recognition is another issue. I haven't dual booted in some time so wasn't aware that issue was still occurring and will look into it. A variation of the fixes you list above are already in my battery patch code however with the Surface Pro devices the DSDT code is quite finicky. Specifically it requires some code to be edited and new code to be added that cannot explicitly be turned off when Windows boots which is what that code above is basically doing. 

Short answer is that it can be fixed but the long answer is that I will have to look over the code and figure out what part of the code is incorrect to resolve that issue. It will take some time as I have a lot going on right now but I will resolve it. I would not recommend attempting to add that code above as it is not complete and is only a portion of what is needed to implement the fix.

**Comment by BT-Lim2021** [comment]
Hi @balopez83,

Thank You for you response.  I much appreciate you responding even though you have a lot going on.
quick update from my end, I managed to work around the issues by installing rEFInd to dual boot.  this way, Windows will boot without Opencore configuration.  So managed to work around battery status.  I also managed to figure out how to continue with secure Boot solution that you provided (with rEFInd).  basically rename refind.efi as grubx64_real.efi and add both windows and opencore efi into the refind config file.  

I did have another issue with the display from the surface I am able to use external monitor via miniDP to HDMI, but miniDP to DisplayPort doesn't work.  Mac (Ventura) does not even recognize there is a display connected.

This is very similar issue #7 surface dock hdmi that was raised by @ShibeGG1.  If you don't mind, I will add additional details in that issue.

**Comment by balopez83** [comment]
Hi @BT-Lim2021 

So I have spent a ton of time on this trying to resolve this issue and in the end I don't believe it is possible. 

Some background as to why: 
Similar to the code you added to the screenshot earlier I had similar code within the SSDT-Surface-Pro_Patches.aml. Unfortunately, with early generation Intel computers like the Surface Pro 3, the DSDT code is based on an earlier ACPI language specification that is generally considered broken. In the case of the Surface Pro 3 the battery and power code is actually broken out into several sections of the EC0 parts of the DSDT and making it worse its not required to be in the same section of the DSDT in that earlier ACPI spec. Editing the code and adding it to the SSDT fixes the battery code for macOS but due to that being based on the latest ACPI spec as macOS requires, Windows gets confused as it is expecting the broken layout. MacOS won't read this using the old spec unless a completely patched DSDT is used. 

Despite my patch being correctly set to use the Windows compatible battery code and reference the unpatched code in the unedited DSDT for some reason Windows cannot correctly read the data. The result is that Windows actually does see the battery but is unable to get data for the battery which is why it doesn't actually show the battery connected even though it does show up in the Device Manager. 

So the only three options to get this working are: 
1. To fully edit the DSDT: Not recommended as it has to be done for all versions of the SP3 and has to be done after every firmware update and when the UEFI has changed settings. 
2. Utilize Refind or Refind Plus to bypass SSDT injection from OpenCore (what you did)
3. Utilize a modded version of OpenCore which is programmed to not inject SSDT's when booting other OS's other than macOS.

I am going to look at options 2 & 3 to see which is the best way forward but since it is not possible to patch for working battery in both OS's at the same time, and I really want dual boot to work properly. Once I find the best solution I will integrate those changes into the next release. Once that happens it will change what you have done at which point you can either redo what you did to keep your configuration or just accept my changes to have it still work pretty much how you wanted. 

Make sure to read the release notes in the next release as it will outline the changes so you can make your decision on how to proceed at that time. I don't know how soon I will get this release pushed but hope to have something issued within the next few days as I have other fixes included as well.

**Comment by balopez83** [comment]
Closing this as resolved with release 6.0.0. Installing Windows alongside macOS is challenging and you found a more than suitable way to get the job done. The latest release will resolve the battery issue you had though there is no issue if you decide to upgrade to this EFI but keep using Refind or Refind+
