### ISSUE TITLE
SD card and cpu temperature issue

### ISSUE THREAD

**Issue by manuhuerta** [balopez83/Surface_Pro_3_Hackintosh#17]
I just upgraded to latest EFI version 6.0.0 and when booting, lost SD Card access and CPU Temperature reading.
I kept version 6.0.0 and just changed SMBIOS to MacBookPro14,1 and got again SD Card access but still no CPU Temperature

With previous version, both were working OK 

Using Surface Pro 3 i5

**Comment by balopez83** [comment]
HI @manuhuerta Thank you for bringing this to my attention. The SD card issue was an oversight as I was fixing another issue restoring an old USB configuration. As it turns out both my old and new configurations were wrong and by sheer luck the new configuration drove the SD card. 

I have a fix that should hopefully continue to resolve the USB and Ethernet on the Surface Hubs and definitely does restore the SD card without changing the SMBIOS. 

As for the CPU temp reading, I am not able to see temperature under either of the configurations with the software I am using. Is there a particular software you are using that I should try in order to see if I can resolve where the change occurred? As for the changes in the configuration between my releases, I don't believe the changes I made should have done anything to CPU temp reading but stranger things have happened when it comes to Surface devices.

I am looking into another little issue I am trying to resolve and will release a fix for the SD card hopefully very quickly.

**Comment by manuhuerta** [comment]
Hi @balopez83 
I use [HWMonitorSMC](https://github.com/CloverHackyColor/HWMonitorSMC2) v2.6.1 tool, reads temp, watts consumption and voltage

**Comment by balopez83** [comment]
Hi @manuhuerta I have resolved the issue and will be issuing the release with fixes soon. I need to clean up a few things and test everything to be sure I don't introduce any new issues but hopefully will have this release issued in the next day.

**Comment by balopez83** [comment]
Hi @manuhuerta I have issued release 6.1.0 which should fix both the CPU sensor and SD card issues. Let me know if you continue to have issues. Just a heads up I changed the SMBIOS to MacBookPro12,1 as it should better provide support and CPU power management.

**Comment by manuhuerta** [comment]
thanks, working perfectly now!
