### ISSUE TITLE
Bootup with Monterey

### ISSUE THREAD

**Issue by qasim185** [balopez83/Surface_Pro_3_Hackintosh#2]
i used your EFI and Olarila Monterey 
1.Bootup with Monterey - My SP3 type cover and touch is broken ( i have surface 3 Type cover ( model 1654 ) are these type cover have same hardware ? beacuse only lights are working and click to wake but keys and trackpads not working ?
2.unable to turn off SIP ( automtically enabled after restart from recovery ) ?

**Comment by balopez83** [comment]
Hi @qasim185 I have tested with both versions of the type cover in Monterey and they should be working fine. Touch should also be working (though requires about 10-11 taps to "start" the touch screen and begin recognizing touch). I suspect the issue is using the hacked version and patches provided by Olarila. I believe Olarila has built in patching software that may be modifying the EFI after install. Specifically, it is likely replacing my custom Voodooi2C kext which is specifically modified to run the Surface Keyboards with full functionality and the touch screen. The standard release of Voodooi2c will break functionality of both. I only test and support the vanilla macOS provided from Apple directly. All appropriate modifications to boot and use macOS on the Surface Pro 3 are already implemented in my EFI releases and so the Olarila version is not needed.

Please try a vanilla macOS install and let me know if you are still having issues. If you are unable to download it from the app store to create a bootable usb there is some guides online for a command based tool that will create your usb in Windows. 

On a different note, I am currently working through some different bugs that keep appearing for me in Big Sur and Monterey and should be releasing a new EFI soon. I mention this because I anticipate changing the SMBIOS which will impact iServices if you attempt to sign in with the current EFI. Also, Ventura is not currently supported as apple has dropped support for the SP3 graphics though I am working on some spoof options that may work.

**Comment by balopez83** [comment]
Hi @qasim185 After looking back at this again I am certain that the Olarila Monterey replaced my custom Voodooi2c-custom.kext with their own version of Voodooi2c.kext If you remove it and replace it with my custom one it should restore your keyboard, trackpad, and touch screen. Sip should not be enabled with my EFI which means it was enabled by the Olarila install and I am unsure how to turn that off. Its possible that you will need to go into recovery and turn it off in terminal though unsure with the Olarila releases.

**Comment by qasim185** [comment]
thanks man for the reply i will check it out
by the way good job for making that possible
also i dont thing ventra is necessary
big and Monterey is enough for us to enjoy

I was shocked with the performance in Monterey and the Vram was 3gb nice
man 😅

**Comment by qasim185** [comment]
i mean touch is working only typecover not working but my screen is broken the touch become irresponsive how can i disable only touch ?

**Comment by balopez83** [comment]
you can send me your config.plist from your EFI and I can see if Olarila changed anything critical though the issue may be Olarila's version of macOS. I have tested Apples vanilla Monterey and don't have any of those issues so I am unable to duplicate this problem.

**Comment by qasim185** [comment]
Everythings fixed i change my typecover to model 1725 its working / i disable SIP through opencore configurator and install Chris wifi driver now wifi works too ! are You working to fix the Graphic issue Flickers in Apps or Videos?

**Comment by balopez83** [comment]
@qasim185 sorry for the very slow reply. I am glad you were able to get the keyboard working and not sure why your original one didn't as it really should have. As for the graphics issue of flickering in apps or videos; unfortunately, there is no way to really fix it. It has to do with the way macOS expects the graphics hardware to work and since the graphics hardware within the SP3 is technically different than any real mac there can be moments when it causes problems. I might suggest playing with the resolution. Sometimes adjusting the resolution can reduce the flickering you experience vs staying on the default setting. There should be a few options available in settings. 

As for being able to play video, that can be challenging. If its DRM enabled video such as Apple TV+ it likely never will work as there is no way for the DRM to validate the SP3 screen as compliant. You can use services like Netflix, HBO max and likely others through the Chrome or Edge browser on macOS but not with Safari. The reason is that Chrome and Edge use software authentication which is why it will work. 

Hope that helps a little
