### ISSUE TITLE
Sleep using power button results into a Reboot!

### ISSUE THREAD

**Issue by johncoco12** [balopez83/Surface_Pro_3_Hackintosh#22]
Using the newest release 8.0.0, When the Surface is in Sleep mode and wakeing the device using the power button will result into a reboot + when you try then to boot into MACOS it will reboot again and than when you choose to boot into MACOS it will boot.

Hardware : Surface Pro 3
CPU : Intel I5
RAM : 4GB
SSD : 128GB
MACOS : Catalina 10.15.7

**Comment by balopez83** [comment]
Hi @johncoco12 , I believe the issue you are experiencing is actually expected. I prob should have been a little clearer in the release notes and the readme but Sleep does not work on Surface devices at all and so the workaround is to use Hibernatemode 25 to attempt to hibernate the computer instead of sleeping. Of course by doing that the computer actually shuts down and simply preserves the state of applications restarting them when the computer boots back up. 

In the case of your computer, I assume your computer is actually turning back on showing the Surface logo and then launches the OpenCore menu? From that point it is expected that OpenCore will reboot the system once macOS is selected/auto started and will bring you back to the OpenCore menu again after the reboot at which point macOS will start back up normally. 

Unfortunately there is no way to get hibernation or sleep working any better than this at this time. This workaround ensures that you don't have the common freeze on attempted sleep or worse, high power draw and high heat while appearing to be asleep. In this case you at least can be sure that the computer will not overheat or keep running in a frozen state. 

If you are experiencing something a little different let me know as there may be another issue. 

By the way, I am going to be releasing another minor update in a few minutes because I did discover an issue that prevents booting Ventura and Sonoma prior to installing the OpenCore Legacy Patcher graphics fix.

**Comment by balopez83** [comment]
@johncoco12 assuming resolved due to no response. Closing issue. If the issue continues and is acting different than expected you may reopen this issue.
