### ISSUE TITLE
iServices (iMessage and FaceTime) not working

### ISSUE THREAD

**Issue by manuhuerta** [balopez83/Surface_Pro_3_Hackintosh#24]
Hi
I upgraded to version 8.0.2 and made sure to log out of all iservices before doing the upgrade but when I installed the new EFI version and turned on my surface, I found that iMessage and FaceTime are not working.  It just keeps login in and doesn't complete the login process.   I repeated the EFI installation a couple of times making sure always to logout of all iservices and still the same.
Everything else seems to be working fine, iCloud, Photos, Notes, etc

Surface Pro 3 i5 8GB RAM
Sonoma 14.2
Applied OC post install patch after installation

**Comment by balopez83** [comment]
Did you remember to regenerate your new serial information and put it in the config.plist? 

The computer version (SMBIOS) changed with the 8.x.x releases so if you're coming from earlier versions you would have needed to generate new serial information.

Make sure you have done that and don't keep trying to sign in too much or Apple will lock your account. If it continues to not work and you have generated and added valid serial information to the config.plist then you may need to reinstall macOS. If Apple locks your account you will need to call them to have it unlocked though that is the least likely issue right now since you say all other iservices are still working

**Comment by manuhuerta** [comment]
Yes, I did regenerate the SMBIOS using latest GenSMBIOS and updated config.plist accordingl.  I used MacBookPro11,1 as suggested.

Will try one more time and if it doesn't work, will try reinstalling macOS.

thanks for the support

**Comment by balopez83** [comment]
@manuhuerta sorry for all the headache. I just added instructions on how to clear the iMessage cache in my Quirks and Fixes link on the main readme page; item 6. 

Try signing out of iCloud again and follow those steps to clear the cache and restart. After you should be able to sign in. If that doesnt work, the only solution I am aware of is to reinstall the OS unfortunately.

**Comment by balopez83** [comment]
To make it easy I pasted the information here:

Open a Finder window and click on your User Name then in a blank area right click and select
Show View Options and from the resulting window select Show Library Folder.

Open the newly revealed Library folder and select Caches
From the Caches folder delete all files and folders beginning with :

com.apple.iCloudHelper
com.apple.imfoundation.IMRemoteURLConnectionAgent
com.apple.Message

In Finder navigate to Username/Library/Preferences and delete all files and folders beginning with

com.apple.iChat.
com.apple.icloud.
com.apple.ids.service
com.apple.imagent.
com.apple.imessage.
com.apple.imservice.

Empty the Trash and Restart.

**Comment by manuhuerta** [comment]
@balopez83  did both alternatives, clearing cache/restarting and doing a full clean install and neither of those worked and getting same results of iMessage and FaceTime not allowing me to login.  Rest of services work fine

**Comment by balopez83** [comment]
@manuhuerta I'm wondering if you have some invalid serial information. Did you validate that the serial information wasn't in use or active in Apple management? 

I would try generating new serial information and repeat clearing cache and see if you can get in.

If you still have your old serial information you could revert to the old SMBIOS information and see if that works. You can also send me your current config and I can double check that it looks ok.

**Comment by manuhuerta** [comment]
@balopez83 
Update:  If I connect  my iPhone via usb cable to tether internet, it works perfectly, I'm able to connect and use iMessage, FaceTime.  So seems to be something related when connected via WiFi.  I use chris1111 Wireless-USB-OC-Big-Sur-Adapter as suggested in your drivers section.

**Comment by balopez83** [comment]
@manuhuerta well that is extremely odd. And the WiFi is actually working when not tethered? Does iMessage continue to work after you unplug and stop tethering?

I can't really think of any reason that would happen at all except if your computer still has something off and perhaps if Ethernet spoofing got messed up or if it was a bad serial number. 

Ethernet spoofing with the nullethernet kext along with its ssdt should just work so that seems unlikely so I am really at a loss on this one.

Did you try to get new serial information yet in case you might have had an invalid serial number that might have actually been registered either by a live computer or by a company?

Are you using an Ethernet adapter connected at the same time even if you're not using it when you use WiFi? If you are that might be doing something weird and causing iMessage to invalidate which then might allow the tethering to override.

Grasping at straws on this one cause it doesn't really make sense if the serials are good.

**Comment by balopez83** [comment]
@manuhuerta were you able to figure this out?

**Comment by balopez83** [comment]
@manuhuerta Assuming this has been resolved. Closing this issue. If you need additional assistance with this issue please reopen.
