### ISSUE TITLE
Version 8.0.0 and onwards have an SMBIOS that causes OCLP to say 'No patches required'

### ISSUE THREAD

**Issue by theholyjosh1** [balopez83/Surface_Pro_3_Hackintosh#26]
Hello, releases 8.0.0 and onwards have the model as MacBookPro11,1 and this causes the issue in #23 in the web installer (got around this by installing big sur first) then when i upgraded to sonoma, i installed OCLP as you would normally then clicked start root patches and it said 'No patches required' and start patching was grayed out. When i downgraded the EFI to release 7.0.0 which had the model in PlatformInfo as: 'MacBookAir8,1' and i booted into macOS, launched OCLP an it worked fine and was able to patch graphics normally. Just thought i should let you know you might want to change the SMBIOS.

Sonoma is running fabulous now and i am righting this on my surface on efi release 7.

**Comment by balopez83** [comment]
@ShibeGG1 are you running the i7 variant of the computer?

Using the 7.x.x releases is not ideal as you will lose significant functionality vs the 8.x.x releases.

The SMBIOS used in the 8.x.x releases is the correct one and should not be the reason for OCLP's failure. The actual reason should always be how the graphics chip identifies itself.

In the case of OCLP, they do not maintain a complete list of all the graphics chips and as a result some graphics patches won't be seen by OCPL as valid even though they are. The ones chosen for the SP are because they have the best support (e.g working mDP out) but don't necessarily work for OCPL detection.

I would recommend first trying another models 8.x.x config instead and seeing if that works for you. For example, if you have an i7 use the one for the i5. Personally, I have the i5 and have not been able to duplicate your issue and so the i5 variant of the config will work. 

After getting a successful install of OCLP, you can then switch back to the correct i7 config and get full graphics support without all the glitching you will experience on the i5 config. 

The reason the 7.x.x configs work is because it used a less compatible graphics patch that just happened to be in the OCLP list.

Hope that helps.

**Comment by balopez83** [comment]
@ShibeGG1 I see from another post you do have the i7. That is the issue. Please try to use the i5 config when you need to install OCLP, this way you don't break iServices.

You can then switch back to the i7 config with the same serial information after install and upgrades.

I can look at finding a more compatible graphics patch in the future but it's impossible for me to test if I break something since I don't have the i7 model. The i7 haswell is very finicky with macOS for some reason.
