### ISSUE TITLE
MacOS 13 and 14 Boot Issue

### ISSUE THREAD

**Issue by anxanluv** [balopez83/Surface_Pro_3_Hackintosh#29]
Sometimes MacOS 13 and 14 get stuck at 25% progress bar and I have to manually force shutdown and then turn it back on, it gets annoying because it's my main machine.

**Comment by balopez83** [comment]
@VeryLinuxuser There may be little that can be done since those versions are not natively supporting the SP3 hardware anymore. 

Is this happening after a cold full power up, after sleep/hibernation, after taking updates, after a reboot? What hardware do you have (i3/i5/i7, memory)?

Can you edit your config to add -v to your boot args and boot in verbose till this happens again. When it happens send at minimum an image of where it freezes or if you can your logs after it freezes. Seeing what is happening on your machine will help diagnose. I have not experienced your issue yet so it will be difficult to diagnose without seeing what was going on when it freezes/crashes.

**Comment by balopez83** [comment]
Closing due to no response/activity. Please open a new ticket if this is still an issue on your machine.
