### ISSUE TITLE
WiFi questions

### ISSUE THREAD

**Issue by kymerea** [balopez83/Surface_Pro_3_Hackintosh#3]
I've just got some questions about the WiFi (and Bluetooth) for this EFI. I do understand that the built in ones and just simply not supported. You mention in a previous issue that for USB wifi dongles that don't have a kext but still have driver to just use some option that appears when "Your computer does not have an ethernet or WiFi card installed". I don't see such option as I only have a windows machine to create an online installer - unless there's some other way of making an offline installer that I don't know about. So what I'm here to ask is there a way to create an offline installer such that I can install drivers when the OS is set up. Or with the current kexts what WiFi Chipsets are supported or what WiFi dongle did you use for your own setup.

**Comment by whao123yahoo** [comment]
any usbwifi can work well

**Comment by theholyjosh1** [comment]
what I do instead of buying a usb dongle is use my phone with usb tethering. I have tried it both on my iPhone and Android. For the iPhone all you need to do is to turn on mobile hotspot then plug your phone into the Surface. On android, go into settings then wifi settings and click on tethering then turn it on. This only works with wifi. I'm not sure if there's a way for bluetooth.

**Comment by balopez83** [comment]
Hi @TheDingOfTheHud , If I understand your question correctly you are looking to create an installer for macOS that has all the "drivers" included? I suspect you are thinking of macOS like Windows where drivers are included or installed? Basically the "drivers" or for macOS the "kexts" are actually already included in the "EFI" of the releases. You still need to install the client software to run your usb wifi adapter. The link to that software is included in the instructions linked in the main page. 

Unfortunately, not every usb dongle will work. You should click the link to the wifi client software (Chris's wifi software) where he has a fairly comprehensive list of wifi dongles that will work. While most wifi dongles that have at some point worked with macOS will likely work I have had some not work so using his list of compatible adapters is key. 

As @ShibeGG1 mentions, using a phone to "tether" is certainly an option however if you don't want to have your phone always connected you will want to get a small wifi "nano" adapter. 

To make things easier you should use the following command/powershell based tool: https://github.com/corpnewt/gibMacOS which will allow you to make the installer in Windows without the need to create a macOS virtual machine or try and find a mac you can borrow first. You will not however be able to "install" or copy the wifi drivers to that installer based on the way it will be formatted. You should simply copy the wifi client software to a usb to "install" after you successfully install macOS. 

Hope that helps.

**Comment by balopez83** [comment]
@TheDingOfTheHud one more recommendation is that you make a macOS Monterey or older installer. macOS Ventura does not have Graphics support out of the box and has to be "fixed" after install. It will not be fun going through the setup process on first boot without graphics working. 

If you start with macOS Monterey or older you can "upgrade" to Ventura and its much easier to then "fix" the graphics. The instructions are linked in my main readme. 

I will be adding a new EFI release soon which has the fix for kernel panic issues when using the Surface Type Cover in macOS Ventura. Installing macOS Monterey or older will also help you avoid those issues until I issue that release. 

Once I release it you will want to replace the EFI folder on both the USB installer and your main Surface SSD in order to boot macOS including Ventura without issues. 

I forgot to also add that you must install the EFI folder on your USB installer in order to boot the macOS installer. Doing so in Windows is difficult as the EFI "drive" is hidden and it is not an intuitive process to mount it and copy the files over. I might suggest also creating a linux live boot disk (Ubuntu is helpful and easy to use) and mount the EFI drive that way. You will need a USB hub to do that process as you will need to access both USB sticks at the same time. Hope that helps

**Comment by kymerea** [comment]
This partly answers my question. I do understand the difference between OC drivers and plain macOS drivers. One of my questions was, with the current Kexts install what WiFi chipsets are supported (e.g. Mediatek, Realtek, Intel, etc). And you mention in #1 that:
> Catalina, Big Sur, and Monterey, should all be able to be installed by simply selecting the option when asked that says something along the lines of "your computer does not have an ethernet or WiFi card installed". You can sign into iCloud stuff after you have been able to get to the desktop and install your USB WiFi card.

Whilst from what I can tell, on windows you are only able to create and Online installer (e.g. recovery based and not the full image), I was wondering if there were some way to create a full installer on windows such that I can install macOS driver after the OS is setup. This is becuase the only USB wifi card I have requires an install in the OS and not a kext or OC driver.

**Comment by balopez83** [comment]
Hi @TheDingOfTheHud As mentioned earlier, I do not have the list of wifi devices that will work but if you go to the Chris1111 software download page on Github it will have the list of supported wifi chipsets. I believe the link to the appropriate wifi client software is on my main readme or one of the instruction pages linked on my main Readme. 

I am not sure of a better way to create a full wifi installer other than the Gibmacos script that I mentioned earlier. If that does not work you can use a Prebuilt VMware image (there are a few on Google) and then download and create the full installer that way. You may be able to use a Linux live usb to create one but I haven't really done that before so not sure how different it will be or if it will work .
