### ISSUE TITLE
inside ventura whenever i try to do the post install rootpatch, the start root patching thing is greyed out inside of post inta

### ISSUE THREAD

**Issue by Rateix** [balopez83/Surface_Pro_3_Hackintosh#30]
(title)
![Screenshot_2024-05-23_at_8 09 20_PM](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/121175601/5967de98-064e-4d3d-b68f-61cbf79711a0)

**Comment by balopez83** [comment]
See closed issue #26 

You need to use the i5 config to install the patch and then switch back to the i7. This will need to be done each time you update and need to reapply the patch. This is an issue of OCLP due to not including the i7 graphics information and not an issue with the EFI itself. Swapping the configs is an annoying but workable workaround. 

If you have already signed into iServices be sure you copy your serial information to the i5 config before booting with it or you will be locked out of iServices and it is a bit frustrating to get it to reactivate.

**Comment by Rateix** [comment]
> See closed issue #26
> 
> You need to use the i5 config to install the patch and then switch back to the i7. This will need to be done each time you update and need to reapply the patch. This is an issue of OCLP due to not including the i7 graphics information and not an issue with the EFI itself. Swapping the configs is an annoying but workable workaround.
> 
> If you have already signed into iServices be sure you copy your serial information to the i5 config before booting with it or you will be locked out of iServices and it is a bit frustrating to get it to reactivate.



> See closed issue #26
> 
> You need to use the i5 config to install the patch and then switch back to the i7. This will need to be done each time you update and need to reapply the patch. This is an issue of OCLP due to not including the i7 graphics information and not an issue with the EFI itself. Swapping the configs is an annoying but workable workaround.
> 
> If you have already signed into iServices be sure you copy your serial information to the i5 config before booting with it or you will be locked out of iServices and it is a bit frustrating to get it to reactivate.

thank you! hardware acceleration now works
