### ISSUE TITLE
No input on mic

### ISSUE THREAD

**Issue by theholyjosh1** [balopez83/Surface_Pro_3_Hackintosh#4]
there's no input coming from the mic at all. I've tried looking at settings but still no. this is quite annoying for FaceTime calls.
Any fixes?

**Comment by balopez83** [comment]
I think this broke with macOS Ventura. I don't have an eta on a fix but will look into it when I get some time. I likely will need to test some new audio kext audio mapping options which take time. I suspect something changed with Ventura that is causing this issue as Ventura actually broke a lot of things since the Surface Pro 3 graphics (which includes audio features) are no longer officially supported by Apple.

**Comment by balopez83** [comment]
Just installed and tested this issue on Monterey and it looks like it is an issue there as well. It is likely an issue with audio mapping still though so need to do some digging. If you have a Bluetooth adapter I might suggest using that though it seems headphones don't work either for a microphone so not sure when I will have this fixed.

**Comment by balopez83** [comment]
@ShibeGG1 I have isolated the issue with the internal mic and the fix will be included in the next EFI release. 

On a side note, plug-in headphones will work but the mic does not seem to be recognized and appears to be hardware related and not something that can be fixed. 

I am going to try and get a release out today, tomorrow at the latest. I am going to close this issue now that it will be resolved with the next release.
